# .streamlit/secrets.toml
[google_credentials]
type = "service_account"
project_id = "positive-design-334517"
private_key_id = "04d49bc565cd9a4d1d694808e495e46125b503aa"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCbTdOk1f4gICX3
P1/o25MJrdVNNm11LSGYiaa3u4qAWp/PpJo1sD1b90SzZyZCKkBM8WIzEr/XLGZ0
PyGbU8bWYlBybKEF3LCXrybEn4O9MsVRmLo3VHEjg10R+qeYB/h3pDOwzeSbDzpq
rhe5x9WNVT26I0ROeB2Tre/V7kHuX5TpyZlRtKHVNFXRIZKZX0Wt8vvxSwb39L0s
kjRn4OITJ66WMHfRuj2xRdbORm24RfJ2ua620LzqpGzEB/XLrHn4l0LeyTMGNZuM
+digGgH1W9sLCbgZCHY01MVKWKNxQlrvXOfue8pLSpTa50NufZGJYu0pFxzxZx1k
VGDwhZoPAgMBAAECggEAJ5Q4AeQ/dXR7+H0ANlnvKSJSH/FlB93OmA9Mm7qB26A8
5jAu1Mvrd0qXCZmaGHaoGHPT8OwwU+gO3EVSjUFWhUBc/CxPBS1vG9kZaja03jzY
KKlhm8Q7aS+LQo+8snQlkGgafE6cmh/RZWqkxUX2WKSGrK9cMxtNfltvqfekedkg
PAA5ifxwGK7spOyr3vNTNdJ2eWLH45uexRSKBbFAlsHCCoQE3AtMCBOKy8kY8Xcq
SV0xKVGF0AR9uMnJOWfervuv/U3VMU69cdnsPJWmNKi8qUGesM6L740d6p8gO5C3
bBpAtBVtl9sNkCrlkwn1e5S1h5o8EXypVpHLRw4/UQKBgQDVtOyJ4R/aJ83LMLA5
iwlDt5owXSA3LuIZq2dk4RUvDoE3lw5ur1yG65nMemB205/zEFRjBXYtBelW1fhI
/fzRaRAQB6zWZSJvBLkMlt/Ixrf01HUqF6iJp917f/EdOmPsgqr54CfdAA9qMaVs
nCbhr9oQiMJuK3MWyou0rMSQ3QKBgQC6CggLslYmiZRxPyd83enS2838G6SlUoG6
Bnc/UmMCE8nb8HqbiqbqvfQYzqSBOwhXvVdeyHUH2oSdnrvNfnzM54hwx2MyrPhW
25VH57knVhQrGFmi94P2gxQ0PoJ0+cJGYGhIwk0oOUm8l0lK0jkgovc7xlDi881L
vVOK3ksR2wKBgFVzY4V6Q/86HTqa/Ev2AT1Xg8rE4eXO1E+JTu1yZsMLHLX6q6Ws
buXv/O5bHIlG81UAeY2imG9GRtgW9JFTJa0iQm72crDDfbJAhDG5fj/M3a+C6Fpt
XVG1koUYUnPqbhwa33zMmYPvyzoeIdQ81/s0EpC77mqY6wr48EXNM0ftAoGAbyVj
HSnUkn2LtATZIJ6r/Y/YhpA1U5fxbSRDxg8Am9MavE310kuJ4aDO3qtGWPbdyx2R
v0zfrmt843ZcGS9CfGCvgUF+IF56l9nkW+szES86KW0I0HYz3uj8/yGBa0V0LfuX
EjETS76+MO/pl8v02WzDbHDVDmI9+swHx2V7UBUCgYBC8A97Dnfi90EIDWdIwfma
AccW+4Qow9wz7Ma2rvEgAYtwq9YHoIa+5CtczRwgWaz+VV6KtT+99K14zMDYYHhD
rNoR969qK0YKANlB9bOk4Et2JLbS49ksGspIb1itDtYGj+MFSMpIdfkV6/s29+Ub
p+wx5U9CtyN9HX0vOZ8jdQ==
-----END PRIVATE KEY-----"""
client_email = "macadata@positive-design-334517.iam.gserviceaccount.com"
client_id = "101230174505335740920"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/macadata%40positive-design-334517.iam.gserviceaccount.com"
universe_domain = "googleapis.com"